name: CI

on: [pull_request]

jobs:
  build:
    name: build review pdf
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '14'
  #  - name: install ubuntu package
  #    run: sudo apt-get update && sudo apt-get install fonts-takao-mincho fonts-takao
    - name: npm install
      run: npm install
    - name: build pdf
      run: npm run build:github-action
    - uses: actions/upload-artifact@master
      with:
        name: build-pdf
        path: ./pdf/output.pdf
