name: CI

on: [pull_request]

jobs:
  build:
    name: build review pdf
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '14'
    - name: npm install
      run: npm install
    - name: build pdf
      run: npm run build:github-action
    - uses: actions/upload-artifact@master
      with:
        name: build-pdf
        path: ./pdf/book.pdf
